### ISSUE TITLE
Publishing for integration

### ISSUE THREAD

**Issue by jeremymailen** [mcassiano/ktlint-html-reporter#1]
Have you published or considered publishing your reporter? It might be useful with your permission, see https://github.com/jeremymailen/kotlinter-gradle/issues/45

**Comment by mcassiano** [comment]
Hi @jeremymailen! I'll work on updating the readme for integration soon, now that the loading reporters from external sources is fixed. Thanks!

**Comment by jeremymailen** [comment]
Thank you sir!

**Comment by mcassiano** [comment]
@jeremymailen yep! updated the readme with instructions on how to use it. it's also on jitpack!
