### ISSUE TITLE
Publish 0.2.0 to jcenter

### ISSUE THREAD

**Issue by jeremymailen** [mcassiano/ktlint-html-reporter#10]
Looking forward to incorporating your latest version into `kotlinter-gradle`!

**Comment by mcassiano** [comment]
Jeez I thought it was out. Sorry about that, let me see what happened. Edit: it was released two days after this issue was created!

**Comment by mcassiano** [comment]
I kinda need help setting up CI though! I have not had the time to work on this lately.
