### ISSUE TITLE
Broken integration with ktlint 0.32.0

### ISSUE THREAD

**Issue by 4brunu** [mcassiano/ktlint-html-reporter#13]
Hey, today the ktlint version 0.32.0 was released and it broke this plugin.

Maybe because this version changed the package name.

Would you be ok with the idea of trying to merge this plugin in ktlint itself to prevent future issues in the future?

And in the meanwhile, could you try to fix this issue?
I will also take a look to see if I can fix it and submit a PR.
Thanks

**Comment by 4brunu** [comment]
@mcassiano this is resolved with the last merged PR, but I would like to know your thoughts on this:
Would you be ok with the idea of trying to merge this plugin in ktlint itself to prevent future issues in the future?

**Comment by mcassiano** [comment]
yeah, absolutely. i think making it part of ktlint could also help with versioning and maybe someone can contribute with a better looking design :)

**Comment by paristote** [comment]
Thanks for fixing the issue. Is it possible to release it please?

**Comment by jbaginski** [comment]
hey @mcassiano, would it be possible to do a release with this fix?

**Comment by mcassiano** [comment]
Hi all! Yes, I’ll publish this on JCenter this weekend (later today probably). Unfortunately this is a manual proccess since I don’t have the time to setup a CI build. Merging this reporter directly into ktlint might help in the future.

**Comment by mcassiano** [comment]
Update: should be available through JitPack under 0.2.1. Uploading to JCenter now.
Update 2: should also be available through JCenter under 0.2.1.

**Comment by jbaginski** [comment]
thanks! 🚀

**Comment by shashachu** [comment]
@mcassiano looks like someone opened up a PR to bring your HTML reporter into the main ktlint project. (https://github.com/pinterest/ktlint/pull/641) I am totally fine with this, but I'd feel better if it were you doing the PR. Would you be willing to open up a PR?

**Comment by mcassiano** [comment]
Hey @shashachu. I instructed @arrmixer on how to open the PR. Feel free to continue the review or ping me if you’re still uncomfortable. I’ll subscribe to updates so I can make any changes if necessary :)

**Comment by shashachu** [comment]
@mcassiano sounds good. Can you just comment on the PR on `ktlint` to confirm that you're approving the change?
