### ISSUE TITLE
Still not working with ktlint 0.32.0

### ISSUE THREAD

**Issue by mtiidla** [mcassiano/ktlint-html-reporter#16]
I had the same problem as #13 and saw how it was fixed with https://github.com/mcassiano/ktlint-html-reporter/pull/14

However, the PR seemed to miss the provider file name change, thus the 0.2.1 release still doesn't work.

I have tried with the correct file name in a fork and published it to Jitpack and it works. You can verify with "--reporter=html,artifact=com.github.mtiidla:ktlint-html-reporter:-SNAPSHOT"

The change is just renaming https://github.com/mcassiano/ktlint-html-reporter/tree/0.2.1/src/main/resources/META-INF/services/com.github.shyiko.ktlint.core.ReporterProvider to `com.pinterest.ktlint.core.ReporterProvider`

Should I open a PR, or you will just change it?

**Comment by mcassiano** [comment]
You can open the PR :) Sorry about this, I'm currently not using this reporter at work so I couldn't tell. I should've seen this during my PR though.

**Comment by mcassiano** [comment]
Should be available through JitPack. I'll upload to jCenter later today.

**Comment by mtiidla** [comment]
Have you been able to upload 0.2.2 to jCenter?

**Comment by mcassiano** [comment]
it's online as 0.2.3. would you mind giving it a try?

**Comment by mtiidla** [comment]
> it's online as 0.2.3. would you mind giving it a try?

It does work with 0.2.3. Thank you!
