### ISSUE TITLE
get deprecated warning message 

### ISSUE THREAD

**Issue by arrmixer** [mcassiano/ktlint-html-reporter#19]
Greetings Mcassiano!

thanks for taking the time for making this html reporter. Whenever, I use the ktlint command I get this message. 

[WARNING] Resolving third party rules/reporters from artifactory is deprecated!
[WARNING] See: https://github.com/pinterest/ktlint/issues/451

It seems they are going to get rid of this feature and just make developers use this reporter from a local jar. I wouldn't mind using it this way. Any advice would be welcomed. 

Thank you.

Angel

**Comment by mcassiano** [comment]
Hi @arrmixer!

Sorry it took me a while to get back to you, Github didn't send me a notification email for this issue, not sure why.

This is an interesting problem. I'll look into this. There were initiatives to migrate this reporter into ktlint's source code so this might fix your issue. You can follow this discussion here: https://github.com/pinterest/ktlint/issues/399.

Thanks for reaching out!

**Comment by mcassiano** [comment]
If you're looking for an immediate solution, try downloading the jar from [here](https://jcenter.bintray.com/me/cassiano/ktlint-html-reporter/0.2.3/).

**Comment by arrmixer** [comment]
Hey @mcassiano sorry for the late reply. I got your reply but completely forget to reply back! My apologies! 

Thanks for your help and continued support on this issue. I’m in the process on integrating Klint at work and really wanted to use your html reporter. 

I’ll leave a reply on the issue thread to get an update. Again great work and thank you!
