### ISSUE TITLE
Request: report with no issues should report that instead of being blank

### ISSUE THREAD

**Issue by autonomousapps** [mcassiano/ktlint-html-reporter#5]
Example of a 0-issue lint report:
![screenshot from 2018-04-03 14-04-49](https://user-images.githubusercontent.com/5402301/38275831-00e56866-3748-11e8-99bb-22aa751112cb.png)

It would be great if this reporter followed that pattern so I don't have to wonder if there's a bug when I see a blank screen :)

**Comment by mcassiano** [comment]
Will definitely add this! Will ping you when ready. I think I should probably make the report prettier! Thanks for the suggestion! 🎉

**Comment by autonomousapps** [comment]
I'm now using this in my production app (via the [kotlinter plugin](https://github.com/jeremymailen/kotlinter-gradle)), and the other day I had my devs freaking out because they thought they had kotlin lint errors, but really it was just that the report was blank! Any eta on this? Also, I'd be open to making a basic PR, which you could prettify later.

**Comment by mcassiano** [comment]
Shoot, it's been month! Sorry about this. I had been assigned a new project at work so I didn't have any time to work on this there and I have been taking the weekends to do other stuff other than programming. I'm working on this right now and I'll write a couple of tests before releasing, but should be out in a few hours. Sorry about this!

**Comment by autonomousapps** [comment]
Thank you!

**Comment by mcassiano** [comment]
Just published a version on bintray and I'll tag master as a new version right now :)

**Comment by autonomousapps** [comment]
Huzzah!

**Comment by mcassiano** [comment]
Give it a try and tell me if anything is wrong :)

**Comment by autonomousapps** [comment]
Hopefully soon!
